// Serverprijslijst — DE BRON VAN WAARHEID voor betalingen.
// GEGENEREERD door scripts/sync-catalog.mjs — niet met de hand aanpassen.
// Wijzig src/data/products.js en draai het script opnieuw.
// 45 producten.
export const CATALOG = {
  'pouf-haze':        { name: "Vloerpouf — Haze", price: 245, max: 1 },
  'pouf-poppy':       { name: "Vloerpouf — Poppy", price: 245, max: 1 },
  'pouf-heather':     { name: "Vloerpouf — Heather", price: 245, max: 1 },
  'pouf-saffron':     { name: "Vloerpouf — Saffron", price: 245, max: 1 },
  'pouf-clay':        { name: "Vloerpouf — Clay", price: 285, max: 1 },
  'pouf-drift':       { name: "Vloerpouf — Drift", price: 245, max: 1 },
  'pouf-indigo':      { name: "Vloerpouf — Indigo", price: 245, max: 1 },
  'pouf-peach':       { name: "Vloerpouf — Peach", price: 245, max: 1 },
  'pouf-chalk':       { name: "Vloerpouf — Chalk", price: 195, max: 1 },
  'pouf-tide':        { name: "Vloerpouf — Tide", price: 245, max: 1 },
  'pouf-blush':       { name: "Vloerpouf — Blush", price: 285, max: 1 },
  'pouf-cinnamon':    { name: "Vloerpouf — Cinnamon", price: 245, max: 1 },
  'pouf-dune':        { name: "Vloerpouf — Dune", price: 285, max: 1 },
  'pouf-rust':        { name: "Vloerpouf — Rust", price: 285, max: 1 },
  'pouf-pebble':      { name: "Vloerpouf — Pebble", price: 245, max: 1 },
  'pouf-solstice':    { name: "Vloerpouf — Solstice", price: 245, max: 1 },
  'pouf-shoal':       { name: "Vloerpouf — Shoal", price: 245, max: 1 },
  'pouf-ember':       { name: "Vloerpouf — Ember", price: 245, max: 1 },
  'pouf-meadow':      { name: "Vloerpouf — Meadow", price: 285, max: 1 },
  'pouf-quill':       { name: "Vloerpouf — Quill", price: 195, max: 1 },
  'pouf-thistle':     { name: "Vloerpouf — Thistle", price: 285, max: 1 },
  'pouf-marigold':    { name: "Vloerpouf — Marigold", price: 285, max: 1 },
  'pouf-signal':      { name: "Vloerpouf — Signal", price: 285, max: 1 },
  'pouf-basalt':      { name: "Vloerpouf — Basalt", price: 285, max: 1 },
  'pouf-ash':         { name: "Vloerpouf — Ash", price: 245, max: 1 },
  'pouf-mist':        { name: "Vloerpouf — Mist", price: 245, max: 1 },
  'pouf-sorrel':      { name: "Vloerpouf — Sorrel", price: 285, max: 1 },
  'pouf-coral':       { name: "Vloerpouf — Coral", price: 285, max: 1 },
  'pouf-foxglove':    { name: "Vloerpouf — Foxglove", price: 285, max: 1 },
  'pouf-apricot':     { name: "Vloerpouf — Apricot", price: 285, max: 1 },
  'pouf-garnet':      { name: "Vloerpouf — Garnet", price: 285, max: 1 },
  'pouf-bloom':       { name: "Vloerpouf — Bloom", price: 245, max: 1 },
  'pouf-kapsa':       { name: "Vloerpouf — Kapsa", price: 245, max: 1 },
  'stoel-laurel':     { name: "Stoel — Laurel", price: 165, max: 20 },
  'krukje-laurel':    { name: "Krukje — Laurel", price: 95, max: 20 },
  'kapstok-doum':     { name: "Kapstok — Doum", price: 285, max: 20 },
  'kussen-atlas':     { name: "Kussen — Atlas", price: 75, max: 20 },
  'kussen-fern':      { name: "Kussen — Fern", price: 75, max: 20 },
  'kussen-cobalt':    { name: "Kussen — Cobalt", price: 75, max: 20 },
  'kussen-sienna':    { name: "Kussen — Sienna", price: 75, max: 20 },
  'kussen-cipher':    { name: "Kussen — Cipher", price: 75, max: 20 },
  'kussen-prism':     { name: "Kussen — Prism", price: 75, max: 20 },
  'kussen-umber':     { name: "Kussen — Umber", price: 75, max: 20 },
  'kussen-flare':     { name: "Kussen — Flare", price: 75, max: 20 },
  'kussen-persimmon': { name: "Kussen — Persimmon", price: 75, max: 20 },
}
