// Serverprijslijst — DE BRON VAN WAARHEID voor betalingen.
// GEGENEREERD door scripts/sync-catalog.mjs — niet met de hand aanpassen.
// Wijzig src/data/products.js en draai het script opnieuw.
// 44 producten.
export const CATALOG = {
  'pouf-haze':     { name: "Vloerpouf — Haze", price: 145, max: 1 },
  'pouf-poppy':    { name: "Vloerpouf — Poppy", price: 145, max: 1 },
  'pouf-heather':  { name: "Vloerpouf — Heather", price: 145, max: 1 },
  'pouf-saffron':  { name: "Vloerpouf — Saffron", price: 145, max: 1 },
  'pouf-clay':     { name: "Vloerpouf — Clay", price: 165, max: 1 },
  'pouf-drift':    { name: "Vloerpouf — Drift", price: 145, max: 1 },
  'pouf-indigo':   { name: "Vloerpouf — Indigo", price: 145, max: 1 },
  'pouf-peach':    { name: "Vloerpouf — Peach", price: 145, max: 1 },
  'pouf-chalk':    { name: "Vloerpouf — Chalk", price: 125, max: 1 },
  'pouf-tide':     { name: "Vloerpouf — Tide", price: 145, max: 1 },
  'pouf-blush':    { name: "Vloerpouf — Blush", price: 165, max: 1 },
  'pouf-cinnamon': { name: "Vloerpouf — Cinnamon", price: 145, max: 1 },
  'pouf-dune':     { name: "Vloerpouf — Dune", price: 165, max: 1 },
  'pouf-rust':     { name: "Vloerpouf — Rust", price: 165, max: 1 },
  'pouf-pebble':   { name: "Vloerpouf — Pebble", price: 145, max: 1 },
  'pouf-solstice': { name: "Vloerpouf — Solstice", price: 145, max: 1 },
  'pouf-shoal':    { name: "Vloerpouf — Shoal", price: 145, max: 1 },
  'pouf-ember':    { name: "Vloerpouf — Ember", price: 145, max: 1 },
  'pouf-meadow':   { name: "Vloerpouf — Meadow", price: 165, max: 1 },
  'pouf-quill':    { name: "Vloerpouf — Quill", price: 125, max: 1 },
  'pouf-thistle':  { name: "Vloerpouf — Thistle", price: 165, max: 1 },
  'pouf-marigold': { name: "Vloerpouf — Marigold", price: 165, max: 1 },
  'pouf-signal':   { name: "Vloerpouf — Signal", price: 165, max: 1 },
  'pouf-basalt':   { name: "Vloerpouf — Basalt", price: 165, max: 1 },
  'pouf-ash':      { name: "Vloerpouf — Ash", price: 145, max: 1 },
  'pouf-mist':     { name: "Vloerpouf — Mist", price: 145, max: 1 },
  'pouf-sorrel':   { name: "Vloerpouf — Sorrel", price: 165, max: 1 },
  'pouf-coral':    { name: "Vloerpouf — Coral", price: 165, max: 1 },
  'pouf-foxglove': { name: "Vloerpouf — Foxglove", price: 165, max: 1 },
  'pouf-apricot':  { name: "Vloerpouf — Apricot", price: 165, max: 1 },
  'pouf-garnet':   { name: "Vloerpouf — Garnet", price: 165, max: 1 },
  'pouf-bloom':    { name: "Vloerpouf — Bloom", price: 145, max: 1 },
  'pouf-kapsa':    { name: "Vloerpouf — Kapsa", price: 145, max: 1 },
  'stoel-laurel':  { name: "Stoel — Laurel", price: 165, max: 20 },
  'krukje-laurel': { name: "Krukje — Laurel", price: 95, max: 20 },
  'kapstok-doum':  { name: "Kapstok — Doum", price: 285, max: 20 },
  'kussen-atlas':  { name: "Kussen — Atlas", price: 75, max: 20 },
  'kussen-fern':   { name: "Kussen — Fern", price: 75, max: 20 },
  'kussen-cobalt': { name: "Kussen — Cobalt", price: 75, max: 20 },
  'kussen-sienna': { name: "Kussen — Sienna", price: 75, max: 20 },
  'kussen-cipher': { name: "Kussen — Cipher", price: 75, max: 20 },
  'kussen-prism':  { name: "Kussen — Prism", price: 75, max: 20 },
  'kussen-umber':  { name: "Kussen — Umber", price: 75, max: 20 },
  'kussen-flare':  { name: "Kussen — Flare", price: 75, max: 20 },
}
